import type { Metadata } from "next"; 
import "./globals.css";
 

export const metadata: Metadata = {
  title: "Anonymous AnuraG - VFX Generalist",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/logo.png",
        sizes: "32x32",
        type: "image/jpg",
      },
      {
        url: "/logo.png",
        sizes: "16x16",
        type: "image/jpg",
      },
    ],
    shortcut: { url: "/logo.png" },
    apple: {
      url: "/logo.png",
      sizes: "180x180",
      type: "image/jpg",
    },
    other: {
      rel: "icon",
      url: "/logo.png",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
