import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Anonymous AnuraG - VFX Generalist",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/anurag.jpg",
        sizes: "32x32",
        type: "image/jpg",
      },
      {
        url: "/anurag.jpg",
        sizes: "16x16",
        type: "image/jpg",
      },
    ],
    shortcut: { url: "/anurag.jpg" },
    apple: {
      url: "/anurag.jpg",
      sizes: "180x180",
      type: "image/jpg",
    },
    other: {
      rel: "icon",
      url: "/anurag.jpg",
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
